upstream songs_api {
    server songs-api:5000;
}

server {
    listen 80;
    server_name _;

    location / {
        return 200 'Automatizador de canciones online';
        add_header Content-Type text/plain;
    }

    location /api/ {
        proxy_pass http://songs_api/;
        proxy_set_header Host $host;
    }
}
